name: "FedEx composite action eg"
description: "FedEx composite action eg steps are mentioned below"

inputs:
  devops-integration-token:
    description: "The token for DevOps integration tool."
    required: true
  # devops-integration-user-name:
  #   description: "The username for DevOps integration."
  #   required: true
  # devops-integration-user-password:
  #   description: "The password for DevOps integration."
  #   required: true
  instance-url:
    description: "The URL of the ServiceNow instance."
    required: true
  job-name:
    description: "The job name for change creation."
    required: true
  tool-id:
    description: "The ID of the Orchestration Tool."
    required: true
  context-github:
    description: "GitHub Context."
    required: true
  # job-name:
  #   description: "GitHub Context."
  #   required: true

runs:
  using: "composite"
  steps:
    # - name: call-composite-action-test
    #   uses: ServiceNow/servicenow-devops-test-report@main
    #   with:
    #     devops-integration-user-name: ${{ inputs.devops-integration-user-name }}
    #     devops-integration-user-password: ${{ inputs.devops-integration-user-password }}
    #     instance-url: 'https://avitokyo4.service-now.com/'
    #     tool-id: ${{ inputs.tool-id }}
    #     job-name: 'call-composite-action-test / Test'
    #     context-github: ${{ inputs.context-github }}
    #     xml-report-filename: valid-xunit.xml

    - name: call-composite-action-change
      uses: ServiceNow/servicenow-devops-change@v4.0.0
      with:
        # devops-integration-user-name: ${{ inputs.devops-integration-user-name }}
        # devops-integration-user-password: ${{ inputs.devops-integration-user-password }}
        devops-integration-token: ${{ inputs.devops-integration-token }}
        instance-url: ${{ inputs.instance-url }}
        tool-id: ${{ inputs.tool-id }}
        context-github: ${{ inputs.context-github }}
        change-request: '{"autoCloseChange":true,"attributes": {"close_notes":"ASD for close notes"}}'
        interval: '100'
        timeout: '3600'
        job-name: ${{ inputs.job-name }}
        
        

    # - name: ServiceNow DevOps Change Automation
    #   uses: ServiceNow/servicenow-devops-change@dev
    #   with:
    #     instance-url: 'https://empkiranv02.service-now.com/'
    #     devops-integration-user-name: ${{ inputs.devops-integration-user-name }}
    #     devops-integration-user-password: ${{ inputs.devops-integration-user-password }}
    #     tool-id: ${{ inputs.tool-id }}
    #     job-name: 'ServiceNow DevOps Change Automation'
    #     context-github: ${{ inputs.context-github }}
    #     timeout: 3600 # optional, default is 3600
    #     interval: 100 # optional, default is 100
    #     # The customized inputs to create change with the requested details.
    #     change-request: '{
    #         "setCloseCode": "true",
    #         "attributes": {
    #             "short_description": "Automated Software Deployment",
    #             "chg_model": "adffaa9e4370211072b7f6be5bb8f2ed",
    #             "description": "Automated Software Deployment.",
    #             "assignment_group": "a715cd759f2002002920bde8132e7018",
    #             "implementation_plan": "Software update is tested and results can be found in Test Summaries Tab.",
    #             "backout_plan": "When software fails in production, the previous software release will be re-deployed.",
    #             "test_plan": "Testing if the software was successfully deployed"
    #         }
    #     }'
